GET http://localhost:5000/todos HTTP/1.1

###
POST http://localhost:5000/todos HTTP/1.1
Content-Type: application/json

{
    "title": "My task number 22"
}

###
DELETE http://localhost:5000/todos/6033899220fbfd5df69f4f9a HTTP/1.1
